// Code generated by protoc-gen-go. DO NOT EDIT.
// source: homecard.proto

package lovers_srv_home

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CARDTYPE int32

const (
	CARDTYPE_AD   CARDTYPE = 0
	CARDTYPE_Info CARDTYPE = 1
)

var CARDTYPE_name = map[int32]string{
	0: "AD",
	1: "Info",
}

var CARDTYPE_value = map[string]int32{
	"AD":   0,
	"Info": 1,
}

func (x CARDTYPE) String() string {
	return proto.EnumName(CARDTYPE_name, int32(x))
}

func (CARDTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{0}
}

type ADTYPE int32

const (
	ADTYPE_HOTEL ADTYPE = 0
	ADTYPE_FOOD  ADTYPE = 1
)

var ADTYPE_name = map[int32]string{
	0: "HOTEL",
	1: "FOOD",
}

var ADTYPE_value = map[string]int32{
	"HOTEL": 0,
	"FOOD":  1,
}

func (x ADTYPE) String() string {
	return proto.EnumName(ADTYPE_name, int32(x))
}

func (ADTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{1}
}

type INFOTYPE int32

const (
	INFOTYPE_NEWS INFOTYPE = 0
)

var INFOTYPE_name = map[int32]string{
	0: "NEWS",
}

var INFOTYPE_value = map[string]int32{
	"NEWS": 0,
}

func (x INFOTYPE) String() string {
	return proto.EnumName(INFOTYPE_name, int32(x))
}

func (INFOTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{2}
}

type HomeCardIndex struct {
	IndexStart           string   `protobuf:"bytes,1,opt,name=IndexStart,proto3" json:"IndexStart,omitempty"`
	IndexEnd             string   `protobuf:"bytes,2,opt,name=IndexEnd,proto3" json:"IndexEnd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeCardIndex) Reset()         { *m = HomeCardIndex{} }
func (m *HomeCardIndex) String() string { return proto.CompactTextString(m) }
func (*HomeCardIndex) ProtoMessage()    {}
func (*HomeCardIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{0}
}

func (m *HomeCardIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeCardIndex.Unmarshal(m, b)
}
func (m *HomeCardIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeCardIndex.Marshal(b, m, deterministic)
}
func (m *HomeCardIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeCardIndex.Merge(m, src)
}
func (m *HomeCardIndex) XXX_Size() int {
	return xxx_messageInfo_HomeCardIndex.Size(m)
}
func (m *HomeCardIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeCardIndex.DiscardUnknown(m)
}

var xxx_messageInfo_HomeCardIndex proto.InternalMessageInfo

func (m *HomeCardIndex) GetIndexStart() string {
	if m != nil {
		return m.IndexStart
	}
	return ""
}

func (m *HomeCardIndex) GetIndexEnd() string {
	if m != nil {
		return m.IndexEnd
	}
	return ""
}

//获取首页卡片状态
type CardRespStatus struct {
	GetCardRes           string   `protobuf:"bytes,1,opt,name=GetCardRes,proto3" json:"GetCardRes,omitempty"`
	GetCardCode          string   `protobuf:"bytes,2,opt,name=GetCardCode,proto3" json:"GetCardCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardRespStatus) Reset()         { *m = CardRespStatus{} }
func (m *CardRespStatus) String() string { return proto.CompactTextString(m) }
func (*CardRespStatus) ProtoMessage()    {}
func (*CardRespStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{1}
}

func (m *CardRespStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardRespStatus.Unmarshal(m, b)
}
func (m *CardRespStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardRespStatus.Marshal(b, m, deterministic)
}
func (m *CardRespStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardRespStatus.Merge(m, src)
}
func (m *CardRespStatus) XXX_Size() int {
	return xxx_messageInfo_CardRespStatus.Size(m)
}
func (m *CardRespStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CardRespStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CardRespStatus proto.InternalMessageInfo

func (m *CardRespStatus) GetGetCardRes() string {
	if m != nil {
		return m.GetCardRes
	}
	return ""
}

func (m *CardRespStatus) GetGetCardCode() string {
	if m != nil {
		return m.GetCardCode
	}
	return ""
}

//首页卡片的基本信息
type HomeCardInfo struct {
	CardType             CARDTYPE `protobuf:"varint,1,opt,name=CardType,proto3,enum=lovers.srv.home.CARDTYPE" json:"CardType,omitempty"`
	AdType               ADTYPE   `protobuf:"varint,2,opt,name=AdType,proto3,enum=lovers.srv.home.ADTYPE" json:"AdType,omitempty"`
	InfoType             INFOTYPE `protobuf:"varint,3,opt,name=InfoType,proto3,enum=lovers.srv.home.INFOTYPE" json:"InfoType,omitempty"`
	ImgUrl               string   `protobuf:"bytes,4,opt,name=ImgUrl,proto3" json:"ImgUrl,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=Content,proto3" json:"Content,omitempty"`
	TypeDesc             string   `protobuf:"bytes,7,opt,name=TypeDesc,proto3" json:"TypeDesc,omitempty"`
	CreateTime           string   `protobuf:"bytes,8,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	ShowIndex            string   `protobuf:"bytes,9,opt,name=ShowIndex,proto3" json:"ShowIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeCardInfo) Reset()         { *m = HomeCardInfo{} }
func (m *HomeCardInfo) String() string { return proto.CompactTextString(m) }
func (*HomeCardInfo) ProtoMessage()    {}
func (*HomeCardInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{2}
}

func (m *HomeCardInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeCardInfo.Unmarshal(m, b)
}
func (m *HomeCardInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeCardInfo.Marshal(b, m, deterministic)
}
func (m *HomeCardInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeCardInfo.Merge(m, src)
}
func (m *HomeCardInfo) XXX_Size() int {
	return xxx_messageInfo_HomeCardInfo.Size(m)
}
func (m *HomeCardInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeCardInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HomeCardInfo proto.InternalMessageInfo

func (m *HomeCardInfo) GetCardType() CARDTYPE {
	if m != nil {
		return m.CardType
	}
	return CARDTYPE_AD
}

func (m *HomeCardInfo) GetAdType() ADTYPE {
	if m != nil {
		return m.AdType
	}
	return ADTYPE_HOTEL
}

func (m *HomeCardInfo) GetInfoType() INFOTYPE {
	if m != nil {
		return m.InfoType
	}
	return INFOTYPE_NEWS
}

func (m *HomeCardInfo) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

func (m *HomeCardInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *HomeCardInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *HomeCardInfo) GetTypeDesc() string {
	if m != nil {
		return m.TypeDesc
	}
	return ""
}

func (m *HomeCardInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *HomeCardInfo) GetShowIndex() string {
	if m != nil {
		return m.ShowIndex
	}
	return ""
}

type GetMainCardReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMainCardReq) Reset()         { *m = GetMainCardReq{} }
func (m *GetMainCardReq) String() string { return proto.CompactTextString(m) }
func (*GetMainCardReq) ProtoMessage()    {}
func (*GetMainCardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{3}
}

func (m *GetMainCardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMainCardReq.Unmarshal(m, b)
}
func (m *GetMainCardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMainCardReq.Marshal(b, m, deterministic)
}
func (m *GetMainCardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMainCardReq.Merge(m, src)
}
func (m *GetMainCardReq) XXX_Size() int {
	return xxx_messageInfo_GetMainCardReq.Size(m)
}
func (m *GetMainCardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMainCardReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMainCardReq proto.InternalMessageInfo

type GetMainCardResp struct {
	RespStatus           *CardRespStatus `protobuf:"bytes,1,opt,name=RespStatus,proto3" json:"RespStatus,omitempty"`
	MainCardInfo         []*HomeCardInfo `protobuf:"bytes,2,rep,name=MainCardInfo,proto3" json:"MainCardInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetMainCardResp) Reset()         { *m = GetMainCardResp{} }
func (m *GetMainCardResp) String() string { return proto.CompactTextString(m) }
func (*GetMainCardResp) ProtoMessage()    {}
func (*GetMainCardResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{4}
}

func (m *GetMainCardResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMainCardResp.Unmarshal(m, b)
}
func (m *GetMainCardResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMainCardResp.Marshal(b, m, deterministic)
}
func (m *GetMainCardResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMainCardResp.Merge(m, src)
}
func (m *GetMainCardResp) XXX_Size() int {
	return xxx_messageInfo_GetMainCardResp.Size(m)
}
func (m *GetMainCardResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMainCardResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMainCardResp proto.InternalMessageInfo

func (m *GetMainCardResp) GetRespStatus() *CardRespStatus {
	if m != nil {
		return m.RespStatus
	}
	return nil
}

func (m *GetMainCardResp) GetMainCardInfo() []*HomeCardInfo {
	if m != nil {
		return m.MainCardInfo
	}
	return nil
}

type PostCardInfoReq struct {
	CardType             CARDTYPE `protobuf:"varint,1,opt,name=CardType,proto3,enum=lovers.srv.home.CARDTYPE" json:"CardType,omitempty"`
	AdType               ADTYPE   `protobuf:"varint,2,opt,name=AdType,proto3,enum=lovers.srv.home.ADTYPE" json:"AdType,omitempty"`
	InfoType             INFOTYPE `protobuf:"varint,3,opt,name=InfoType,proto3,enum=lovers.srv.home.INFOTYPE" json:"InfoType,omitempty"`
	ImgUrl               string   `protobuf:"bytes,4,opt,name=ImgUrl,proto3" json:"ImgUrl,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=Content,proto3" json:"Content,omitempty"`
	TypeDesc             string   `protobuf:"bytes,7,opt,name=TypeDesc,proto3" json:"TypeDesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostCardInfoReq) Reset()         { *m = PostCardInfoReq{} }
func (m *PostCardInfoReq) String() string { return proto.CompactTextString(m) }
func (*PostCardInfoReq) ProtoMessage()    {}
func (*PostCardInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{5}
}

func (m *PostCardInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCardInfoReq.Unmarshal(m, b)
}
func (m *PostCardInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCardInfoReq.Marshal(b, m, deterministic)
}
func (m *PostCardInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCardInfoReq.Merge(m, src)
}
func (m *PostCardInfoReq) XXX_Size() int {
	return xxx_messageInfo_PostCardInfoReq.Size(m)
}
func (m *PostCardInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCardInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_PostCardInfoReq proto.InternalMessageInfo

func (m *PostCardInfoReq) GetCardType() CARDTYPE {
	if m != nil {
		return m.CardType
	}
	return CARDTYPE_AD
}

func (m *PostCardInfoReq) GetAdType() ADTYPE {
	if m != nil {
		return m.AdType
	}
	return ADTYPE_HOTEL
}

func (m *PostCardInfoReq) GetInfoType() INFOTYPE {
	if m != nil {
		return m.InfoType
	}
	return INFOTYPE_NEWS
}

func (m *PostCardInfoReq) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

func (m *PostCardInfoReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostCardInfoReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PostCardInfoReq) GetTypeDesc() string {
	if m != nil {
		return m.TypeDesc
	}
	return ""
}

type PostCardInfoResp struct {
	RespStatus           *CardRespStatus `protobuf:"bytes,1,opt,name=RespStatus,proto3" json:"RespStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PostCardInfoResp) Reset()         { *m = PostCardInfoResp{} }
func (m *PostCardInfoResp) String() string { return proto.CompactTextString(m) }
func (*PostCardInfoResp) ProtoMessage()    {}
func (*PostCardInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{6}
}

func (m *PostCardInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCardInfoResp.Unmarshal(m, b)
}
func (m *PostCardInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCardInfoResp.Marshal(b, m, deterministic)
}
func (m *PostCardInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCardInfoResp.Merge(m, src)
}
func (m *PostCardInfoResp) XXX_Size() int {
	return xxx_messageInfo_PostCardInfoResp.Size(m)
}
func (m *PostCardInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCardInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_PostCardInfoResp proto.InternalMessageInfo

func (m *PostCardInfoResp) GetRespStatus() *CardRespStatus {
	if m != nil {
		return m.RespStatus
	}
	return nil
}

func init() {
	proto.RegisterEnum("lovers.srv.home.CARDTYPE", CARDTYPE_name, CARDTYPE_value)
	proto.RegisterEnum("lovers.srv.home.ADTYPE", ADTYPE_name, ADTYPE_value)
	proto.RegisterEnum("lovers.srv.home.INFOTYPE", INFOTYPE_name, INFOTYPE_value)
	proto.RegisterType((*HomeCardIndex)(nil), "lovers.srv.home.HomeCardIndex")
	proto.RegisterType((*CardRespStatus)(nil), "lovers.srv.home.CardRespStatus")
	proto.RegisterType((*HomeCardInfo)(nil), "lovers.srv.home.HomeCardInfo")
	proto.RegisterType((*GetMainCardReq)(nil), "lovers.srv.home.GetMainCardReq")
	proto.RegisterType((*GetMainCardResp)(nil), "lovers.srv.home.GetMainCardResp")
	proto.RegisterType((*PostCardInfoReq)(nil), "lovers.srv.home.PostCardInfoReq")
	proto.RegisterType((*PostCardInfoResp)(nil), "lovers.srv.home.PostCardInfoResp")
}

func init() { proto.RegisterFile("homecard.proto", fileDescriptor_44d5d343b9799012) }

var fileDescriptor_44d5d343b9799012 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0xdd, 0xc4, 0x75, 0x26, 0x21, 0xb1, 0x46, 0x15, 0x2c, 0x51, 0x0b, 0xc1, 0xa7, 0x2a,
	0x07, 0x23, 0x05, 0x71, 0x46, 0x96, 0x93, 0xb6, 0x11, 0xd0, 0x54, 0xb6, 0x2b, 0xc4, 0xd1, 0xc4,
	0x0b, 0x8d, 0x94, 0x78, 0x5d, 0x7b, 0x29, 0xf0, 0x1f, 0xf0, 0x21, 0x7c, 0x09, 0xbf, 0x84, 0x76,
	0x6d, 0xc7, 0x76, 0x2c, 0xe0, 0xc2, 0xb1, 0x37, 0xcf, 0x9b, 0x79, 0x6f, 0x76, 0xdf, 0xdb, 0x04,
	0x06, 0x37, 0x6c, 0x4b, 0x57, 0x41, 0x12, 0x5a, 0x71, 0xc2, 0x38, 0xc3, 0xe1, 0x86, 0xdd, 0xd1,
	0x24, 0xb5, 0xd2, 0xe4, 0xce, 0x12, 0x2d, 0xf3, 0x35, 0x3c, 0xb8, 0x60, 0x5b, 0xea, 0x04, 0x49,
	0xb8, 0x88, 0x42, 0xfa, 0x15, 0x9f, 0x00, 0xc8, 0x0f, 0x8f, 0x07, 0x09, 0x27, 0xca, 0x58, 0x39,
	0xed, 0xba, 0x15, 0x04, 0x47, 0xa0, 0xcb, 0x6a, 0x1e, 0x85, 0x44, 0x95, 0xdd, 0x5d, 0x6d, 0xba,
	0x30, 0x10, 0x42, 0x2e, 0x4d, 0x63, 0x8f, 0x07, 0xfc, 0x73, 0x2a, 0xd4, 0xce, 0x29, 0xcf, 0xc1,
	0x42, 0xad, 0x44, 0x70, 0x0c, 0xbd, 0xbc, 0x72, 0x58, 0x48, 0x73, 0xc1, 0x2a, 0x64, 0xfe, 0x52,
	0xa1, 0x5f, 0x9e, 0xf0, 0x23, 0xc3, 0x97, 0xa0, 0x8b, 0x6f, 0xff, 0x5b, 0x4c, 0xa5, 0xe0, 0x60,
	0xfa, 0xd8, 0xda, 0xbb, 0x95, 0xe5, 0xd8, 0xee, 0xcc, 0x7f, 0x7f, 0x35, 0x77, 0x77, 0xa3, 0xf8,
	0x1c, 0x34, 0x3b, 0x23, 0xa9, 0x92, 0xf4, 0xa8, 0x41, 0xb2, 0x33, 0x4a, 0x3e, 0x26, 0xf6, 0x88,
	0x7d, 0x92, 0x72, 0xf0, 0x87, 0x3d, 0x8b, 0xcb, 0xb3, 0x65, 0xb6, 0xa7, 0x18, 0xc5, 0x87, 0xa0,
	0x2d, 0xb6, 0x9f, 0xae, 0x93, 0x0d, 0x69, 0xcb, 0xcb, 0xe4, 0x15, 0x1e, 0x41, 0xc7, 0x5f, 0xf3,
	0x0d, 0x25, 0x1d, 0x09, 0x67, 0x05, 0x12, 0x38, 0x74, 0x58, 0xc4, 0x69, 0xc4, 0x89, 0x26, 0xf1,
	0xa2, 0x14, 0x3e, 0x0b, 0xbd, 0x19, 0x4d, 0x57, 0xe4, 0x30, 0xf3, 0xb9, 0xa8, 0x85, 0xab, 0x4e,
	0x42, 0x03, 0x4e, 0xfd, 0xf5, 0x96, 0x12, 0x3d, 0x73, 0xb5, 0x44, 0xf0, 0x18, 0xba, 0xde, 0x0d,
	0xfb, 0x22, 0x73, 0x21, 0x5d, 0xd9, 0x2e, 0x01, 0xd3, 0x80, 0xc1, 0x39, 0xe5, 0x6f, 0x83, 0x75,
	0x94, 0xa5, 0x70, 0x6b, 0xfe, 0x50, 0x60, 0x58, 0x83, 0xd2, 0x18, 0x5f, 0x01, 0x94, 0x39, 0x4a,
	0xa3, 0x7b, 0xd3, 0xa7, 0x4d, 0xa3, 0x6b, 0x71, 0xbb, 0x15, 0x0a, 0xda, 0xd0, 0x2f, 0x04, 0x85,
	0x39, 0x44, 0x1d, 0x1f, 0x9c, 0xf6, 0xa6, 0x27, 0x0d, 0x89, 0x6a, 0xb8, 0x6e, 0x8d, 0x62, 0x7e,
	0x57, 0x61, 0x78, 0xc5, 0x52, 0xbe, 0x6b, 0xd3, 0xdb, 0xfb, 0xf8, 0x57, 0xa6, 0x07, 0x46, 0xdd,
	0x95, 0xff, 0x10, 0xd7, 0xe4, 0x18, 0xf4, 0xc2, 0x36, 0xd4, 0x40, 0xb5, 0x67, 0x46, 0x0b, 0x75,
	0x68, 0x8b, 0x05, 0x86, 0x32, 0x39, 0x01, 0x2d, 0xf3, 0x07, 0xbb, 0xd0, 0xb9, 0x58, 0xfa, 0xf3,
	0x37, 0x59, 0xfb, 0x6c, 0xb9, 0x9c, 0x19, 0xca, 0xe4, 0x08, 0xf4, 0xc2, 0x0b, 0x81, 0x5e, 0xce,
	0xdf, 0x79, 0x46, 0x6b, 0xfa, 0x53, 0x81, 0xb6, 0x58, 0x8b, 0xae, 0xfc, 0x95, 0x17, 0xd1, 0x62,
	0xf3, 0x5c, 0xf5, 0xf7, 0x38, 0x1a, 0xff, 0x7d, 0x20, 0x8d, 0xcd, 0x16, 0x5e, 0x43, 0xbf, 0x6a,
	0x02, 0x36, 0x39, 0x7b, 0x2f, 0x67, 0xf4, 0xec, 0x1f, 0x13, 0x42, 0xf6, 0x83, 0x26, 0xff, 0x27,
	0x5f, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x86, 0xb7, 0x3c, 0x26, 0x39, 0x05, 0x00, 0x00,
}
