// Code generated by protoc-gen-go. DO NOT EDIT.
// source: homecard.proto

package lovers_srv_home

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CARDTYPE int32

const (
	CARDTYPE_CARDTYPE_UNKNOWN CARDTYPE = 0
	CARDTYPE_AD               CARDTYPE = 1
	CARDTYPE_Info             CARDTYPE = 2
)

var CARDTYPE_name = map[int32]string{
	0: "CARDTYPE_UNKNOWN",
	1: "AD",
	2: "Info",
}

var CARDTYPE_value = map[string]int32{
	"CARDTYPE_UNKNOWN": 0,
	"AD":               1,
	"Info":             2,
}

func (x CARDTYPE) String() string {
	return proto.EnumName(CARDTYPE_name, int32(x))
}

func (CARDTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{0}
}

type ADTYPE int32

const (
	ADTYPE_ADTYPE_UNKNOWN ADTYPE = 0
	ADTYPE_HOTEL          ADTYPE = 1
	ADTYPE_FOOD           ADTYPE = 2
)

var ADTYPE_name = map[int32]string{
	0: "ADTYPE_UNKNOWN",
	1: "HOTEL",
	2: "FOOD",
}

var ADTYPE_value = map[string]int32{
	"ADTYPE_UNKNOWN": 0,
	"HOTEL":          1,
	"FOOD":           2,
}

func (x ADTYPE) String() string {
	return proto.EnumName(ADTYPE_name, int32(x))
}

func (ADTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{1}
}

type INFOTYPE int32

const (
	INFOTYPE_INFOTYPE_UNKNOWN INFOTYPE = 0
	INFOTYPE_NEWS             INFOTYPE = 1
)

var INFOTYPE_name = map[int32]string{
	0: "INFOTYPE_UNKNOWN",
	1: "NEWS",
}

var INFOTYPE_value = map[string]int32{
	"INFOTYPE_UNKNOWN": 0,
	"NEWS":             1,
}

func (x INFOTYPE) String() string {
	return proto.EnumName(INFOTYPE_name, int32(x))
}

func (INFOTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{2}
}

type MEDIATYPE int32

const (
	MEDIATYPE_MEDIATYPE_UNKNOWN MEDIATYPE = 0
	MEDIATYPE_IMAGE             MEDIATYPE = 1
	MEDIATYPE_AUDIO             MEDIATYPE = 2
)

var MEDIATYPE_name = map[int32]string{
	0: "MEDIATYPE_UNKNOWN",
	1: "IMAGE",
	2: "AUDIO",
}

var MEDIATYPE_value = map[string]int32{
	"MEDIATYPE_UNKNOWN": 0,
	"IMAGE":             1,
	"AUDIO":             2,
}

func (x MEDIATYPE) String() string {
	return proto.EnumName(MEDIATYPE_name, int32(x))
}

func (MEDIATYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{3}
}

//获取首页卡片状态
type CardRespStatus struct {
	OpCardRes            string   `protobuf:"bytes,1,opt,name=OpCardRes,proto3" json:"OpCardRes,omitempty"`
	OpCardCode           int32    `protobuf:"varint,2,opt,name=OpCardCode,proto3" json:"OpCardCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardRespStatus) Reset()         { *m = CardRespStatus{} }
func (m *CardRespStatus) String() string { return proto.CompactTextString(m) }
func (*CardRespStatus) ProtoMessage()    {}
func (*CardRespStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{0}
}

func (m *CardRespStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardRespStatus.Unmarshal(m, b)
}
func (m *CardRespStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardRespStatus.Marshal(b, m, deterministic)
}
func (m *CardRespStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardRespStatus.Merge(m, src)
}
func (m *CardRespStatus) XXX_Size() int {
	return xxx_messageInfo_CardRespStatus.Size(m)
}
func (m *CardRespStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CardRespStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CardRespStatus proto.InternalMessageInfo

func (m *CardRespStatus) GetOpCardRes() string {
	if m != nil {
		return m.OpCardRes
	}
	return ""
}

func (m *CardRespStatus) GetOpCardCode() int32 {
	if m != nil {
		return m.OpCardCode
	}
	return 0
}

//首页卡片的基本信息
type HomeCardInfo struct {
	// @inject_tag: form:"CardType"
	CardType CARDTYPE `protobuf:"varint,1,opt,name=CardType,proto3,enum=lovers.srv.home.CARDTYPE" json:"CardType,omitempty" form:"CardType"`
	// @inject_tag: form:"AdType"
	AdType ADTYPE `protobuf:"varint,2,opt,name=AdType,proto3,enum=lovers.srv.home.ADTYPE" json:"AdType,omitempty" form:"AdType"`
	// @inject_tag: form:"InfoType"
	InfoType INFOTYPE `protobuf:"varint,3,opt,name=InfoType,proto3,enum=lovers.srv.home.INFOTYPE" json:"InfoType,omitempty" form:"InfoType"`
	// @inject_tag: form:"Title"
	Title string `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty" form:"Title"`
	// @inject_tag: form:"Content"
	Content string `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty" form:"Content"`
	// @inject_tag: form:"HomeHtmlUrl"
	HomeHtmlUrl string `protobuf:"bytes,6,opt,name=HomeHtmlUrl,proto3" json:"HomeHtmlUrl,omitempty" form:"HomeHtmlUrl"`
	// @inject_tag: form:"TypeDesc"
	TypeDesc string `protobuf:"bytes,7,opt,name=TypeDesc,proto3" json:"TypeDesc,omitempty" form:"TypeDesc"`
	// @inject_tag: form:"CreateTime"
	CreateTime int64 `protobuf:"varint,8,opt,name=CreateTime,proto3" json:"CreateTime,omitempty" form:"CreateTime"`
	// @inject_tag: form:"ShowIndex"
	ShowIndex int32 `protobuf:"varint,9,opt,name=ShowIndex,proto3" json:"ShowIndex,omitempty" form:"ShowIndex"`
	// @inject_tag: form:"IsMainCard"
	IsMainCard bool `protobuf:"varint,10,opt,name=IsMainCard,proto3" json:"IsMainCard,omitempty" form:"IsMainCard"`
	// @inject_tag: form:"UpLoadUserId" binding:"required"
	UpLoadUserId string `protobuf:"bytes,11,opt,name=UpLoadUserId,proto3" json:"UpLoadUserId,omitempty" form:"UpLoadUserId" binding:"required"`
	// @inject_tag: form:"CardId"
	CardId string `protobuf:"bytes,12,opt,name=CardId,proto3" json:"CardId,omitempty" form:"CardId"`
	// @inject_tag: form:"HomeImgUrl"
	HomeImgUrl string `protobuf:"bytes,13,opt,name=HomeImgUrl,proto3" json:"HomeImgUrl,omitempty" form:"HomeImgUrl"`
	// @inject_tag: form:"CardMediaType"
	CardMediaType MEDIATYPE `protobuf:"varint,14,opt,name=CardMediaType,proto3,enum=lovers.srv.home.MEDIATYPE" json:"CardMediaType,omitempty" form:"CardMediaType"`
	// @inject_tag: form:"AudioFileUrl"
	AudioFileUrl string `protobuf:"bytes,15,opt,name=AudioFileUrl,proto3" json:"AudioFileUrl,omitempty" form:"AudioFileUrl"`
	// @inject_tag: form:"AudioLength"
	AudioLength          string   `protobuf:"bytes,16,opt,name=AudioLength,proto3" json:"AudioLength,omitempty" form:"AudioLength"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeCardInfo) Reset()         { *m = HomeCardInfo{} }
func (m *HomeCardInfo) String() string { return proto.CompactTextString(m) }
func (*HomeCardInfo) ProtoMessage()    {}
func (*HomeCardInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{1}
}

func (m *HomeCardInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeCardInfo.Unmarshal(m, b)
}
func (m *HomeCardInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeCardInfo.Marshal(b, m, deterministic)
}
func (m *HomeCardInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeCardInfo.Merge(m, src)
}
func (m *HomeCardInfo) XXX_Size() int {
	return xxx_messageInfo_HomeCardInfo.Size(m)
}
func (m *HomeCardInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeCardInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HomeCardInfo proto.InternalMessageInfo

func (m *HomeCardInfo) GetCardType() CARDTYPE {
	if m != nil {
		return m.CardType
	}
	return CARDTYPE_CARDTYPE_UNKNOWN
}

func (m *HomeCardInfo) GetAdType() ADTYPE {
	if m != nil {
		return m.AdType
	}
	return ADTYPE_ADTYPE_UNKNOWN
}

func (m *HomeCardInfo) GetInfoType() INFOTYPE {
	if m != nil {
		return m.InfoType
	}
	return INFOTYPE_INFOTYPE_UNKNOWN
}

func (m *HomeCardInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *HomeCardInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *HomeCardInfo) GetHomeHtmlUrl() string {
	if m != nil {
		return m.HomeHtmlUrl
	}
	return ""
}

func (m *HomeCardInfo) GetTypeDesc() string {
	if m != nil {
		return m.TypeDesc
	}
	return ""
}

func (m *HomeCardInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *HomeCardInfo) GetShowIndex() int32 {
	if m != nil {
		return m.ShowIndex
	}
	return 0
}

func (m *HomeCardInfo) GetIsMainCard() bool {
	if m != nil {
		return m.IsMainCard
	}
	return false
}

func (m *HomeCardInfo) GetUpLoadUserId() string {
	if m != nil {
		return m.UpLoadUserId
	}
	return ""
}

func (m *HomeCardInfo) GetCardId() string {
	if m != nil {
		return m.CardId
	}
	return ""
}

func (m *HomeCardInfo) GetHomeImgUrl() string {
	if m != nil {
		return m.HomeImgUrl
	}
	return ""
}

func (m *HomeCardInfo) GetCardMediaType() MEDIATYPE {
	if m != nil {
		return m.CardMediaType
	}
	return MEDIATYPE_MEDIATYPE_UNKNOWN
}

func (m *HomeCardInfo) GetAudioFileUrl() string {
	if m != nil {
		return m.AudioFileUrl
	}
	return ""
}

func (m *HomeCardInfo) GetAudioLength() string {
	if m != nil {
		return m.AudioLength
	}
	return ""
}

type GetMainCardReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMainCardReq) Reset()         { *m = GetMainCardReq{} }
func (m *GetMainCardReq) String() string { return proto.CompactTextString(m) }
func (*GetMainCardReq) ProtoMessage()    {}
func (*GetMainCardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{2}
}

func (m *GetMainCardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMainCardReq.Unmarshal(m, b)
}
func (m *GetMainCardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMainCardReq.Marshal(b, m, deterministic)
}
func (m *GetMainCardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMainCardReq.Merge(m, src)
}
func (m *GetMainCardReq) XXX_Size() int {
	return xxx_messageInfo_GetMainCardReq.Size(m)
}
func (m *GetMainCardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMainCardReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMainCardReq proto.InternalMessageInfo

func (m *GetMainCardReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetMainCardResp struct {
	RespStatus           *CardRespStatus `protobuf:"bytes,1,opt,name=RespStatus,proto3" json:"RespStatus,omitempty"`
	MainCardInfo         []*HomeCardInfo `protobuf:"bytes,2,rep,name=MainCardInfo,proto3" json:"MainCardInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetMainCardResp) Reset()         { *m = GetMainCardResp{} }
func (m *GetMainCardResp) String() string { return proto.CompactTextString(m) }
func (*GetMainCardResp) ProtoMessage()    {}
func (*GetMainCardResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{3}
}

func (m *GetMainCardResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMainCardResp.Unmarshal(m, b)
}
func (m *GetMainCardResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMainCardResp.Marshal(b, m, deterministic)
}
func (m *GetMainCardResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMainCardResp.Merge(m, src)
}
func (m *GetMainCardResp) XXX_Size() int {
	return xxx_messageInfo_GetMainCardResp.Size(m)
}
func (m *GetMainCardResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMainCardResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMainCardResp proto.InternalMessageInfo

func (m *GetMainCardResp) GetRespStatus() *CardRespStatus {
	if m != nil {
		return m.RespStatus
	}
	return nil
}

func (m *GetMainCardResp) GetMainCardInfo() []*HomeCardInfo {
	if m != nil {
		return m.MainCardInfo
	}
	return nil
}

type GetCardByCountReq struct {
	StartTime            int64    `protobuf:"varint,1,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              int64    `protobuf:"varint,2,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	CardCount            int32    `protobuf:"varint,3,opt,name=CardCount,proto3" json:"CardCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCardByCountReq) Reset()         { *m = GetCardByCountReq{} }
func (m *GetCardByCountReq) String() string { return proto.CompactTextString(m) }
func (*GetCardByCountReq) ProtoMessage()    {}
func (*GetCardByCountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{4}
}

func (m *GetCardByCountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCardByCountReq.Unmarshal(m, b)
}
func (m *GetCardByCountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCardByCountReq.Marshal(b, m, deterministic)
}
func (m *GetCardByCountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCardByCountReq.Merge(m, src)
}
func (m *GetCardByCountReq) XXX_Size() int {
	return xxx_messageInfo_GetCardByCountReq.Size(m)
}
func (m *GetCardByCountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCardByCountReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCardByCountReq proto.InternalMessageInfo

func (m *GetCardByCountReq) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *GetCardByCountReq) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *GetCardByCountReq) GetCardCount() int32 {
	if m != nil {
		return m.CardCount
	}
	return 0
}

type GetCardByCountResp struct {
	CardList             []*HomeCardInfo `protobuf:"bytes,1,rep,name=CardList,proto3" json:"CardList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetCardByCountResp) Reset()         { *m = GetCardByCountResp{} }
func (m *GetCardByCountResp) String() string { return proto.CompactTextString(m) }
func (*GetCardByCountResp) ProtoMessage()    {}
func (*GetCardByCountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{5}
}

func (m *GetCardByCountResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCardByCountResp.Unmarshal(m, b)
}
func (m *GetCardByCountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCardByCountResp.Marshal(b, m, deterministic)
}
func (m *GetCardByCountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCardByCountResp.Merge(m, src)
}
func (m *GetCardByCountResp) XXX_Size() int {
	return xxx_messageInfo_GetCardByCountResp.Size(m)
}
func (m *GetCardByCountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCardByCountResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetCardByCountResp proto.InternalMessageInfo

func (m *GetCardByCountResp) GetCardList() []*HomeCardInfo {
	if m != nil {
		return m.CardList
	}
	return nil
}

type PostCardInfoReq struct {
	PostCardInfo         *HomeCardInfo `protobuf:"bytes,1,opt,name=PostCardInfo,proto3" json:"PostCardInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PostCardInfoReq) Reset()         { *m = PostCardInfoReq{} }
func (m *PostCardInfoReq) String() string { return proto.CompactTextString(m) }
func (*PostCardInfoReq) ProtoMessage()    {}
func (*PostCardInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{6}
}

func (m *PostCardInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCardInfoReq.Unmarshal(m, b)
}
func (m *PostCardInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCardInfoReq.Marshal(b, m, deterministic)
}
func (m *PostCardInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCardInfoReq.Merge(m, src)
}
func (m *PostCardInfoReq) XXX_Size() int {
	return xxx_messageInfo_PostCardInfoReq.Size(m)
}
func (m *PostCardInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCardInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_PostCardInfoReq proto.InternalMessageInfo

func (m *PostCardInfoReq) GetPostCardInfo() *HomeCardInfo {
	if m != nil {
		return m.PostCardInfo
	}
	return nil
}

type PostCardInfoResp struct {
	RespStatus           *CardRespStatus `protobuf:"bytes,1,opt,name=RespStatus,proto3" json:"RespStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PostCardInfoResp) Reset()         { *m = PostCardInfoResp{} }
func (m *PostCardInfoResp) String() string { return proto.CompactTextString(m) }
func (*PostCardInfoResp) ProtoMessage()    {}
func (*PostCardInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_44d5d343b9799012, []int{7}
}

func (m *PostCardInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCardInfoResp.Unmarshal(m, b)
}
func (m *PostCardInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCardInfoResp.Marshal(b, m, deterministic)
}
func (m *PostCardInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCardInfoResp.Merge(m, src)
}
func (m *PostCardInfoResp) XXX_Size() int {
	return xxx_messageInfo_PostCardInfoResp.Size(m)
}
func (m *PostCardInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCardInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_PostCardInfoResp proto.InternalMessageInfo

func (m *PostCardInfoResp) GetRespStatus() *CardRespStatus {
	if m != nil {
		return m.RespStatus
	}
	return nil
}

func init() {
	proto.RegisterEnum("lovers.srv.home.CARDTYPE", CARDTYPE_name, CARDTYPE_value)
	proto.RegisterEnum("lovers.srv.home.ADTYPE", ADTYPE_name, ADTYPE_value)
	proto.RegisterEnum("lovers.srv.home.INFOTYPE", INFOTYPE_name, INFOTYPE_value)
	proto.RegisterEnum("lovers.srv.home.MEDIATYPE", MEDIATYPE_name, MEDIATYPE_value)
	proto.RegisterType((*CardRespStatus)(nil), "lovers.srv.home.CardRespStatus")
	proto.RegisterType((*HomeCardInfo)(nil), "lovers.srv.home.HomeCardInfo")
	proto.RegisterType((*GetMainCardReq)(nil), "lovers.srv.home.GetMainCardReq")
	proto.RegisterType((*GetMainCardResp)(nil), "lovers.srv.home.GetMainCardResp")
	proto.RegisterType((*GetCardByCountReq)(nil), "lovers.srv.home.GetCardByCountReq")
	proto.RegisterType((*GetCardByCountResp)(nil), "lovers.srv.home.GetCardByCountResp")
	proto.RegisterType((*PostCardInfoReq)(nil), "lovers.srv.home.PostCardInfoReq")
	proto.RegisterType((*PostCardInfoResp)(nil), "lovers.srv.home.PostCardInfoResp")
}

func init() { proto.RegisterFile("homecard.proto", fileDescriptor_44d5d343b9799012) }

var fileDescriptor_44d5d343b9799012 = []byte{
	// 715 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcf, 0x6e, 0xda, 0x4e,
	0x10, 0x8e, 0x1d, 0x20, 0x66, 0x20, 0xe0, 0xac, 0xf2, 0xfb, 0x75, 0x8b, 0xfa, 0x87, 0xfa, 0x84,
	0x38, 0x50, 0x95, 0xaa, 0x52, 0x7b, 0x6a, 0x5d, 0x20, 0x89, 0x55, 0xc0, 0x91, 0x01, 0x45, 0x3d,
	0x55, 0x6e, 0xbc, 0x4d, 0x2c, 0x81, 0xed, 0xd8, 0x4b, 0xda, 0x3c, 0x48, 0x1f, 0xa4, 0x0f, 0xd4,
	0x77, 0xa9, 0x66, 0x8d, 0x61, 0x0d, 0x6a, 0xd3, 0x43, 0x6f, 0x3b, 0xdf, 0xcc, 0x37, 0xb3, 0xf3,
	0xed, 0x8c, 0x0d, 0xb5, 0xeb, 0x70, 0xc1, 0x2e, 0xdd, 0xd8, 0xeb, 0x44, 0x71, 0xc8, 0x43, 0x52,
	0x9f, 0x87, 0xb7, 0x2c, 0x4e, 0x3a, 0x49, 0x7c, 0xdb, 0x41, 0x97, 0x31, 0x86, 0x5a, 0xcf, 0x8d,
	0x3d, 0x87, 0x25, 0xd1, 0x84, 0xbb, 0x7c, 0x99, 0x90, 0x47, 0x50, 0xb6, 0xa3, 0x15, 0x46, 0x95,
	0xa6, 0xd2, 0x2a, 0x3b, 0x1b, 0x80, 0x3c, 0x01, 0x48, 0x8d, 0x5e, 0xe8, 0x31, 0xaa, 0x36, 0x95,
	0x56, 0xd1, 0x91, 0x10, 0xe3, 0x67, 0x01, 0xaa, 0x67, 0xe1, 0x82, 0x21, 0x60, 0x05, 0x5f, 0x42,
	0xf2, 0x0a, 0x34, 0x3c, 0x4f, 0xef, 0x22, 0x26, 0xb2, 0xd5, 0xba, 0x0f, 0x3b, 0x5b, 0x97, 0xe8,
	0xf4, 0x4c, 0xa7, 0x3f, 0xfd, 0x78, 0x3e, 0x70, 0xd6, 0xa1, 0xe4, 0x39, 0x94, 0xcc, 0x94, 0xa4,
	0x0a, 0xd2, 0x83, 0x1d, 0x92, 0x99, 0x52, 0x56, 0x61, 0x58, 0x07, 0xeb, 0x09, 0xca, 0xfe, 0x6f,
	0xea, 0x58, 0xe3, 0x13, 0x3b, 0xad, 0x93, 0x85, 0x92, 0x63, 0x28, 0x4e, 0x7d, 0x3e, 0x67, 0xb4,
	0x20, 0x3a, 0x4d, 0x0d, 0x42, 0xe1, 0xa0, 0x17, 0x06, 0x9c, 0x05, 0x9c, 0x16, 0x05, 0x9e, 0x99,
	0xa4, 0x09, 0x15, 0x6c, 0xef, 0x8c, 0x2f, 0xe6, 0xb3, 0x78, 0x4e, 0x4b, 0xc2, 0x2b, 0x43, 0xa4,
	0x01, 0x1a, 0x66, 0xee, 0xb3, 0xe4, 0x92, 0x1e, 0x08, 0xf7, 0xda, 0x46, 0xf5, 0x7a, 0x31, 0x73,
	0x39, 0x9b, 0xfa, 0x0b, 0x46, 0xb5, 0xa6, 0xd2, 0xda, 0x77, 0x24, 0x04, 0xb5, 0x9f, 0x5c, 0x87,
	0x5f, 0xad, 0xc0, 0x63, 0xdf, 0x68, 0x59, 0x88, 0xbb, 0x01, 0x90, 0x6d, 0x25, 0x23, 0xd7, 0x0f,
	0x50, 0x25, 0x0a, 0x4d, 0xa5, 0xa5, 0x39, 0x12, 0x42, 0x0c, 0xa8, 0xce, 0xa2, 0x61, 0xe8, 0x7a,
	0xb3, 0x84, 0xc5, 0x96, 0x47, 0x2b, 0xa2, 0x7a, 0x0e, 0x23, 0xff, 0x43, 0x49, 0x3c, 0x8d, 0x47,
	0xab, 0xc2, 0xbb, 0xb2, 0x30, 0x37, 0x36, 0x61, 0x2d, 0xae, 0xb0, 0xad, 0x43, 0xe1, 0x93, 0x10,
	0xf2, 0x0e, 0x0e, 0x31, 0x72, 0xc4, 0x3c, 0xdf, 0x15, 0x1a, 0xd7, 0x84, 0xc6, 0x8d, 0x1d, 0x8d,
	0x47, 0x83, 0xbe, 0x65, 0x0a, 0x91, 0xf3, 0x04, 0xbc, 0x9d, 0xb9, 0xf4, 0xfc, 0xf0, 0xc4, 0x9f,
	0x33, 0xac, 0x51, 0x4f, 0x6f, 0x27, 0x63, 0xa8, 0xae, 0xb0, 0x87, 0x2c, 0xb8, 0xe2, 0xd7, 0x54,
	0x4f, 0xd5, 0x95, 0x20, 0xa3, 0x05, 0xb5, 0x53, 0xc6, 0xb3, 0x96, 0x1d, 0x76, 0x83, 0x1d, 0xad,
	0xfa, 0x4d, 0x87, 0x75, 0x65, 0x19, 0xdf, 0x15, 0xa8, 0xe7, 0x42, 0x93, 0x88, 0xbc, 0x05, 0xd8,
	0x4c, 0xba, 0x88, 0xaf, 0x74, 0x9f, 0xee, 0x8e, 0x63, 0x6e, 0x21, 0x1c, 0x89, 0x42, 0x4c, 0xa8,
	0x66, 0x09, 0x71, 0x84, 0xa8, 0xda, 0xdc, 0x6f, 0x55, 0xba, 0x8f, 0x77, 0x52, 0xc8, 0x2b, 0xe0,
	0xe4, 0x28, 0x86, 0x0f, 0x47, 0xa7, 0x8c, 0xa3, 0xf9, 0xfe, 0xae, 0x17, 0x2e, 0x03, 0x8e, 0x4d,
	0xe0, 0xc3, 0x73, 0x37, 0xe6, 0x62, 0x2e, 0x14, 0x31, 0x17, 0x1b, 0x00, 0xc7, 0x71, 0x10, 0x78,
	0xc2, 0xa7, 0x0a, 0x5f, 0x66, 0x22, 0x2f, 0x5d, 0xbd, 0x65, 0xc0, 0xc5, 0xd8, 0x17, 0x9d, 0x0d,
	0x60, 0xd8, 0x40, 0xb6, 0x4b, 0x25, 0x11, 0x79, 0x93, 0x6e, 0xe4, 0xd0, 0x4f, 0x38, 0x55, 0xfe,
	0xe6, 0xfe, 0xeb, 0x70, 0x63, 0x0a, 0xf5, 0xf3, 0x30, 0xe1, 0x6b, 0x0f, 0xbb, 0x41, 0x45, 0x64,
	0x68, 0x25, 0xea, 0x7d, 0x8a, 0xc8, 0x14, 0x63, 0x02, 0x7a, 0x3e, 0xeb, 0x3f, 0x78, 0xa9, 0x76,
	0x17, 0xb4, 0xec, 0xb3, 0x42, 0x8e, 0x41, 0xcf, 0xce, 0x9f, 0x66, 0xe3, 0x0f, 0x63, 0xfb, 0x62,
	0xac, 0xef, 0x91, 0x12, 0xa8, 0x66, 0x5f, 0x57, 0x88, 0x06, 0x05, 0x2c, 0xab, 0xab, 0xed, 0x17,
	0x50, 0x4a, 0xbf, 0x2a, 0x84, 0x40, 0xcd, 0xdc, 0x8e, 0x2f, 0x43, 0xf1, 0xcc, 0x9e, 0x0e, 0x86,
	0x29, 0xe5, 0xc4, 0xb6, 0xfb, 0xba, 0xda, 0x6e, 0x83, 0x96, 0x7d, 0x55, 0xb0, 0x4c, 0x76, 0x96,
	0x68, 0x1a, 0x14, 0xc6, 0x83, 0x8b, 0x89, 0xae, 0xb4, 0x5f, 0x43, 0x79, 0xbd, 0x1d, 0xe4, 0x3f,
	0x38, 0x5a, 0x1b, 0xf9, 0x22, 0xd6, 0xc8, 0x3c, 0x1d, 0xe8, 0x0a, 0x1e, 0xcd, 0x59, 0xdf, 0xb2,
	0x75, 0xb5, 0xfb, 0x43, 0x81, 0x02, 0x36, 0x4c, 0x1c, 0xa8, 0x48, 0x33, 0x4d, 0x76, 0x15, 0xc9,
	0x2f, 0x47, 0xa3, 0xf9, 0xe7, 0x80, 0x24, 0x32, 0xf6, 0xc8, 0x2c, 0xff, 0x82, 0x64, 0x97, 0xb3,
	0xf5, 0xe6, 0x8d, 0x67, 0xf7, 0x44, 0x60, 0xda, 0xcf, 0x25, 0xf1, 0xc7, 0x79, 0xf9, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x1e, 0xe0, 0x75, 0x4c, 0x83, 0x06, 0x00, 0x00,
}
