// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: fileserver.proto

package lovers_srv_file

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DownLoadFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID          string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	DownLoadFileUrl string `protobuf:"bytes,2,opt,name=DownLoadFileUrl,proto3" json:"DownLoadFileUrl,omitempty"`
}

func (x *DownLoadFileReq) Reset() {
	*x = DownLoadFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownLoadFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownLoadFileReq) ProtoMessage() {}

func (x *DownLoadFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_fileserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownLoadFileReq.ProtoReflect.Descriptor instead.
func (*DownLoadFileReq) Descriptor() ([]byte, []int) {
	return file_fileserver_proto_rawDescGZIP(), []int{0}
}

func (x *DownLoadFileReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DownLoadFileReq) GetDownLoadFileUrl() string {
	if x != nil {
		return x.DownLoadFileUrl
	}
	return ""
}

type DownLoadFileResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID          string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	FileBinData     []byte `protobuf:"bytes,2,opt,name=FileBinData,proto3" json:"FileBinData,omitempty"`
	DownLoadFileRet string `protobuf:"bytes,3,opt,name=DownLoadFileRet,proto3" json:"DownLoadFileRet,omitempty"`
}

func (x *DownLoadFileResp) Reset() {
	*x = DownLoadFileResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownLoadFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownLoadFileResp) ProtoMessage() {}

func (x *DownLoadFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_fileserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownLoadFileResp.ProtoReflect.Descriptor instead.
func (*DownLoadFileResp) Descriptor() ([]byte, []int) {
	return file_fileserver_proto_rawDescGZIP(), []int{1}
}

func (x *DownLoadFileResp) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DownLoadFileResp) GetFileBinData() []byte {
	if x != nil {
		return x.FileBinData
	}
	return nil
}

func (x *DownLoadFileResp) GetDownLoadFileRet() string {
	if x != nil {
		return x.DownLoadFileRet
	}
	return ""
}

type UpLoadFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	FileInModule string `protobuf:"bytes,2,opt,name=FileInModule,proto3" json:"FileInModule,omitempty"` //属于哪个模块的文件
	FileType     string `protobuf:"bytes,3,opt,name=FileType,proto3" json:"FileType,omitempty"`         //image, txt...
	FileName     string `protobuf:"bytes,4,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FileBinData  []byte `protobuf:"bytes,5,opt,name=FileBinData,proto3" json:"FileBinData,omitempty"`
}

func (x *UpLoadFileReq) Reset() {
	*x = UpLoadFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpLoadFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpLoadFileReq) ProtoMessage() {}

func (x *UpLoadFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_fileserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpLoadFileReq.ProtoReflect.Descriptor instead.
func (*UpLoadFileReq) Descriptor() ([]byte, []int) {
	return file_fileserver_proto_rawDescGZIP(), []int{2}
}

func (x *UpLoadFileReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UpLoadFileReq) GetFileInModule() string {
	if x != nil {
		return x.FileInModule
	}
	return ""
}

func (x *UpLoadFileReq) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *UpLoadFileReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UpLoadFileReq) GetFileBinData() []byte {
	if x != nil {
		return x.FileBinData
	}
	return nil
}

type UpLoadFileResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpLoadFileUrl string `protobuf:"bytes,1,opt,name=UpLoadFileUrl,proto3" json:"UpLoadFileUrl,omitempty"`
	UpLoadFileRet string `protobuf:"bytes,2,opt,name=UpLoadFileRet,proto3" json:"UpLoadFileRet,omitempty"`
	FileUrl       string `protobuf:"bytes,3,opt,name=FileUrl,proto3" json:"FileUrl,omitempty"`
	UserID        string `protobuf:"bytes,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *UpLoadFileResp) Reset() {
	*x = UpLoadFileResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpLoadFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpLoadFileResp) ProtoMessage() {}

func (x *UpLoadFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_fileserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpLoadFileResp.ProtoReflect.Descriptor instead.
func (*UpLoadFileResp) Descriptor() ([]byte, []int) {
	return file_fileserver_proto_rawDescGZIP(), []int{3}
}

func (x *UpLoadFileResp) GetUpLoadFileUrl() string {
	if x != nil {
		return x.UpLoadFileUrl
	}
	return ""
}

func (x *UpLoadFileResp) GetUpLoadFileRet() string {
	if x != nil {
		return x.UpLoadFileRet
	}
	return ""
}

func (x *UpLoadFileResp) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *UpLoadFileResp) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type DelFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID  string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	FileUrl string `protobuf:"bytes,2,opt,name=FileUrl,proto3" json:"FileUrl,omitempty"`
}

func (x *DelFileReq) Reset() {
	*x = DelFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFileReq) ProtoMessage() {}

func (x *DelFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_fileserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFileReq.ProtoReflect.Descriptor instead.
func (*DelFileReq) Descriptor() ([]byte, []int) {
	return file_fileserver_proto_rawDescGZIP(), []int{4}
}

func (x *DelFileReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DelFileReq) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

type DelFileResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID     string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	DelFileRet string `protobuf:"bytes,2,opt,name=DelFileRet,proto3" json:"DelFileRet,omitempty"`
}

func (x *DelFileResp) Reset() {
	*x = DelFileResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFileResp) ProtoMessage() {}

func (x *DelFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_fileserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFileResp.ProtoReflect.Descriptor instead.
func (*DelFileResp) Descriptor() ([]byte, []int) {
	return file_fileserver_proto_rawDescGZIP(), []int{5}
}

func (x *DelFileResp) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DelFileResp) GetDelFileRet() string {
	if x != nil {
		return x.DelFileRet
	}
	return ""
}

var File_fileserver_proto protoreflect.FileDescriptor

var file_fileserver_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x22, 0x53, 0x0a, 0x0f, 0x44, 0x6f, 0x77, 0x6e, 0x4c, 0x6f, 0x61, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x28,
	0x0a, 0x0f, 0x44, 0x6f, 0x77, 0x6e, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x44, 0x6f, 0x77, 0x6e, 0x4c, 0x6f, 0x61,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x76, 0x0a, 0x10, 0x44, 0x6f, 0x77, 0x6e,
	0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x69, 0x6e, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x42,
	0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x0f, 0x44, 0x6f, 0x77, 0x6e, 0x4c, 0x6f,
	0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x44, 0x6f, 0x77, 0x6e, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x74,
	0x22, 0xa5, 0x01, 0x0a, 0x0d, 0x55, 0x70, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x46, 0x69,
	0x6c, 0x65, 0x49, 0x6e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x69,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x46, 0x69, 0x6c,
	0x65, 0x42, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x8e, 0x01, 0x0a, 0x0e, 0x55, 0x70, 0x4c,
	0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x0d, 0x55,
	0x70, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x55, 0x70, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72,
	0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x55, 0x70, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x55, 0x70, 0x4c, 0x6f, 0x61, 0x64,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x55,
	0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x3e, 0x0a, 0x0a, 0x44, 0x65, 0x6c,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x45, 0x0a, 0x0b, 0x44, 0x65, 0x6c,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x65, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x74,
	0x32, 0xfc, 0x01, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x55, 0x0a, 0x0c, 0x44, 0x6f, 0x77, 0x6e, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x20, 0x2e, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x66, 0x69, 0x6c,
	0x65, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x21, 0x2e, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0a, 0x55, 0x70, 0x4c, 0x6f, 0x61, 0x64,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x1e, 0x2e, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x72,
	0x76, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x55, 0x70, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x72,
	0x76, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x55, 0x70, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x72, 0x76, 0x2e,
	0x66, 0x69, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x1c, 0x2e, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x66, 0x69, 0x6c,
	0x65, 0x2e, 0x44, 0x65, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fileserver_proto_rawDescOnce sync.Once
	file_fileserver_proto_rawDescData = file_fileserver_proto_rawDesc
)

func file_fileserver_proto_rawDescGZIP() []byte {
	file_fileserver_proto_rawDescOnce.Do(func() {
		file_fileserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_fileserver_proto_rawDescData)
	})
	return file_fileserver_proto_rawDescData
}

var file_fileserver_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_fileserver_proto_goTypes = []interface{}{
	(*DownLoadFileReq)(nil),  // 0: lovers.srv.file.DownLoadFileReq
	(*DownLoadFileResp)(nil), // 1: lovers.srv.file.DownLoadFileResp
	(*UpLoadFileReq)(nil),    // 2: lovers.srv.file.UpLoadFileReq
	(*UpLoadFileResp)(nil),   // 3: lovers.srv.file.UpLoadFileResp
	(*DelFileReq)(nil),       // 4: lovers.srv.file.DelFileReq
	(*DelFileResp)(nil),      // 5: lovers.srv.file.DelFileResp
}
var file_fileserver_proto_depIdxs = []int32{
	0, // 0: lovers.srv.file.FileServer.DownLoadFile:input_type -> lovers.srv.file.DownLoadFileReq
	2, // 1: lovers.srv.file.FileServer.UpLoadFile:input_type -> lovers.srv.file.UpLoadFileReq
	4, // 2: lovers.srv.file.FileServer.DelFile:input_type -> lovers.srv.file.DelFileReq
	1, // 3: lovers.srv.file.FileServer.DownLoadFile:output_type -> lovers.srv.file.DownLoadFileResp
	3, // 4: lovers.srv.file.FileServer.UpLoadFile:output_type -> lovers.srv.file.UpLoadFileResp
	5, // 5: lovers.srv.file.FileServer.DelFile:output_type -> lovers.srv.file.DelFileResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fileserver_proto_init() }
func file_fileserver_proto_init() {
	if File_fileserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fileserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownLoadFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownLoadFileResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpLoadFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpLoadFileResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelFileResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fileserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fileserver_proto_goTypes,
		DependencyIndexes: file_fileserver_proto_depIdxs,
		MessageInfos:      file_fileserver_proto_msgTypes,
	}.Build()
	File_fileserver_proto = out.File
	file_fileserver_proto_rawDesc = nil
	file_fileserver_proto_goTypes = nil
	file_fileserver_proto_depIdxs = nil
}
