// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package lovers_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//登录信息
type LoginInfo struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	PassWord             string   `protobuf:"bytes,3,opt,name=PassWord,proto3" json:"PassWord,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginInfo) Reset()         { *m = LoginInfo{} }
func (m *LoginInfo) String() string { return proto.CompactTextString(m) }
func (*LoginInfo) ProtoMessage()    {}
func (*LoginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *LoginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginInfo.Unmarshal(m, b)
}
func (m *LoginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginInfo.Marshal(b, m, deterministic)
}
func (m *LoginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfo.Merge(m, src)
}
func (m *LoginInfo) XXX_Size() int {
	return xxx_messageInfo_LoginInfo.Size(m)
}
func (m *LoginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfo proto.InternalMessageInfo

func (m *LoginInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginInfo) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *LoginInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoginInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

//用户基本信息
type BaseInfo struct {
	UserId               string     `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	RealName             string     `protobuf:"bytes,2,opt,name=RealName,proto3" json:"RealName,omitempty"`
	Phone                string     `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Sex                  string     `protobuf:"bytes,4,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Birth                string     `protobuf:"bytes,5,opt,name=Birth,proto3" json:"Birth,omitempty"`
	Sculpture            string     `protobuf:"bytes,6,opt,name=Sculpture,proto3" json:"Sculpture,omitempty"`
	HomeTown             string     `protobuf:"bytes,7,opt,name=HomeTown,proto3" json:"HomeTown,omitempty"`
	AnotherInfo          *LoverInfo `protobuf:"bytes,8,opt,name=AnotherInfo,proto3" json:"AnotherInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BaseInfo) Reset()         { *m = BaseInfo{} }
func (m *BaseInfo) String() string { return proto.CompactTextString(m) }
func (*BaseInfo) ProtoMessage()    {}
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *BaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfo.Unmarshal(m, b)
}
func (m *BaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfo.Marshal(b, m, deterministic)
}
func (m *BaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfo.Merge(m, src)
}
func (m *BaseInfo) XXX_Size() int {
	return xxx_messageInfo_BaseInfo.Size(m)
}
func (m *BaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfo proto.InternalMessageInfo

func (m *BaseInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *BaseInfo) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *BaseInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *BaseInfo) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *BaseInfo) GetBirth() string {
	if m != nil {
		return m.Birth
	}
	return ""
}

func (m *BaseInfo) GetSculpture() string {
	if m != nil {
		return m.Sculpture
	}
	return ""
}

func (m *BaseInfo) GetHomeTown() string {
	if m != nil {
		return m.HomeTown
	}
	return ""
}

func (m *BaseInfo) GetAnotherInfo() *LoverInfo {
	if m != nil {
		return m.AnotherInfo
	}
	return nil
}

//另一半信息
type LoverInfo struct {
	LoverId              string   `protobuf:"bytes,1,opt,name=LoverId,proto3" json:"LoverId,omitempty"`
	LoverPhone           string   `protobuf:"bytes,2,opt,name=LoverPhone,proto3" json:"LoverPhone,omitempty"`
	LoverNickName        string   `protobuf:"bytes,3,opt,name=LoverNickName,proto3" json:"LoverNickName,omitempty"`
	LoveDuration         string   `protobuf:"bytes,4,opt,name=LoveDuration,proto3" json:"LoveDuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoverInfo) Reset()         { *m = LoverInfo{} }
func (m *LoverInfo) String() string { return proto.CompactTextString(m) }
func (*LoverInfo) ProtoMessage()    {}
func (*LoverInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *LoverInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoverInfo.Unmarshal(m, b)
}
func (m *LoverInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoverInfo.Marshal(b, m, deterministic)
}
func (m *LoverInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoverInfo.Merge(m, src)
}
func (m *LoverInfo) XXX_Size() int {
	return xxx_messageInfo_LoverInfo.Size(m)
}
func (m *LoverInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoverInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoverInfo proto.InternalMessageInfo

func (m *LoverInfo) GetLoverId() string {
	if m != nil {
		return m.LoverId
	}
	return ""
}

func (m *LoverInfo) GetLoverPhone() string {
	if m != nil {
		return m.LoverPhone
	}
	return ""
}

func (m *LoverInfo) GetLoverNickName() string {
	if m != nil {
		return m.LoverNickName
	}
	return ""
}

func (m *LoverInfo) GetLoveDuration() string {
	if m != nil {
		return m.LoveDuration
	}
	return ""
}

type LoginReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	PassWord             string   `protobuf:"bytes,2,opt,name=PassWord,proto3" json:"PassWord,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	VertifyCode          string   `protobuf:"bytes,5,opt,name=VertifyCode,proto3" json:"VertifyCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginReq) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *LoginReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LoginReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoginReq) GetVertifyCode() string {
	if m != nil {
		return m.VertifyCode
	}
	return ""
}

type LoginResp struct {
	Token                string    `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	UserInfo             *BaseInfo `protobuf:"bytes,2,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
	LoginTime            string    `protobuf:"bytes,3,opt,name=LoginTime,proto3" json:"LoginTime,omitempty"`
	LoginRes             string    `protobuf:"bytes,4,opt,name=LoginRes,proto3" json:"LoginRes,omitempty"`
	LoginCode            string    `protobuf:"bytes,5,opt,name=LoginCode,proto3" json:"LoginCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResp) GetUserInfo() *BaseInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *LoginResp) GetLoginTime() string {
	if m != nil {
		return m.LoginTime
	}
	return ""
}

func (m *LoginResp) GetLoginRes() string {
	if m != nil {
		return m.LoginRes
	}
	return ""
}

func (m *LoginResp) GetLoginCode() string {
	if m != nil {
		return m.LoginCode
	}
	return ""
}

type LogoutReq struct {
	Phone                string   `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutReq) Reset()         { *m = LogoutReq{} }
func (m *LogoutReq) String() string { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()    {}
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *LogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReq.Unmarshal(m, b)
}
func (m *LogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReq.Marshal(b, m, deterministic)
}
func (m *LogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReq.Merge(m, src)
}
func (m *LogoutReq) XXX_Size() int {
	return xxx_messageInfo_LogoutReq.Size(m)
}
func (m *LogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReq proto.InternalMessageInfo

func (m *LogoutReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LogoutReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type LogoutResp struct {
	Phone                string   `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	LogoutTime           string   `protobuf:"bytes,2,opt,name=LogoutTime,proto3" json:"LogoutTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResp) Reset()         { *m = LogoutResp{} }
func (m *LogoutResp) String() string { return proto.CompactTextString(m) }
func (*LogoutResp) ProtoMessage()    {}
func (*LogoutResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *LogoutResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResp.Unmarshal(m, b)
}
func (m *LogoutResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResp.Marshal(b, m, deterministic)
}
func (m *LogoutResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResp.Merge(m, src)
}
func (m *LogoutResp) XXX_Size() int {
	return xxx_messageInfo_LogoutResp.Size(m)
}
func (m *LogoutResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResp.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResp proto.InternalMessageInfo

func (m *LogoutResp) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LogoutResp) GetLogoutTime() string {
	if m != nil {
		return m.LogoutTime
	}
	return ""
}

type RegisterReq struct {
	UserName             string    `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	PassWord             string    `protobuf:"bytes,2,opt,name=PassWord,proto3" json:"PassWord,omitempty"`
	UserInfo             *BaseInfo `protobuf:"bytes,3,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
	BindId               string    `protobuf:"bytes,4,opt,name=BindId,proto3" json:"BindId,omitempty"`
	RecommendID          string    `protobuf:"bytes,5,opt,name=RecommendID,proto3" json:"RecommendID,omitempty"`
	VertifyCode          string    `protobuf:"bytes,6,opt,name=VertifyCode,proto3" json:"VertifyCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterReq) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *RegisterReq) GetUserInfo() *BaseInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *RegisterReq) GetBindId() string {
	if m != nil {
		return m.BindId
	}
	return ""
}

func (m *RegisterReq) GetRecommendID() string {
	if m != nil {
		return m.RecommendID
	}
	return ""
}

func (m *RegisterReq) GetVertifyCode() string {
	if m != nil {
		return m.VertifyCode
	}
	return ""
}

type RegisterResp struct {
	RegisteredInfo       *LoginResp `protobuf:"bytes,1,opt,name=RegisteredInfo,proto3" json:"RegisteredInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetRegisteredInfo() *LoginResp {
	if m != nil {
		return m.RegisteredInfo
	}
	return nil
}

type BindLoverReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`
	BindLoverId          string   `protobuf:"bytes,3,opt,name=BindLoverId,proto3" json:"BindLoverId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindLoverReq) Reset()         { *m = BindLoverReq{} }
func (m *BindLoverReq) String() string { return proto.CompactTextString(m) }
func (*BindLoverReq) ProtoMessage()    {}
func (*BindLoverReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *BindLoverReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindLoverReq.Unmarshal(m, b)
}
func (m *BindLoverReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindLoverReq.Marshal(b, m, deterministic)
}
func (m *BindLoverReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindLoverReq.Merge(m, src)
}
func (m *BindLoverReq) XXX_Size() int {
	return xxx_messageInfo_BindLoverReq.Size(m)
}
func (m *BindLoverReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BindLoverReq.DiscardUnknown(m)
}

var xxx_messageInfo_BindLoverReq proto.InternalMessageInfo

func (m *BindLoverReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *BindLoverReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *BindLoverReq) GetBindLoverId() string {
	if m != nil {
		return m.BindLoverId
	}
	return ""
}

type BindLoverResp struct {
	BindLoverInfo        *LoverInfo `protobuf:"bytes,1,opt,name=BindLoverInfo,proto3" json:"BindLoverInfo,omitempty"`
	BindTime             string     `protobuf:"bytes,2,opt,name=BindTime,proto3" json:"BindTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BindLoverResp) Reset()         { *m = BindLoverResp{} }
func (m *BindLoverResp) String() string { return proto.CompactTextString(m) }
func (*BindLoverResp) ProtoMessage()    {}
func (*BindLoverResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *BindLoverResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindLoverResp.Unmarshal(m, b)
}
func (m *BindLoverResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindLoverResp.Marshal(b, m, deterministic)
}
func (m *BindLoverResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindLoverResp.Merge(m, src)
}
func (m *BindLoverResp) XXX_Size() int {
	return xxx_messageInfo_BindLoverResp.Size(m)
}
func (m *BindLoverResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BindLoverResp.DiscardUnknown(m)
}

var xxx_messageInfo_BindLoverResp proto.InternalMessageInfo

func (m *BindLoverResp) GetBindLoverInfo() *LoverInfo {
	if m != nil {
		return m.BindLoverInfo
	}
	return nil
}

func (m *BindLoverResp) GetBindTime() string {
	if m != nil {
		return m.BindTime
	}
	return ""
}

type UnBindLoverReq struct {
	UserId               string     `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Phone                string     `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`
	PassWord             string     `protobuf:"bytes,3,opt,name=PassWord,proto3" json:"PassWord,omitempty"`
	UnBindLoverInfo      *LoverInfo `protobuf:"bytes,4,opt,name=UnBindLoverInfo,proto3" json:"UnBindLoverInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UnBindLoverReq) Reset()         { *m = UnBindLoverReq{} }
func (m *UnBindLoverReq) String() string { return proto.CompactTextString(m) }
func (*UnBindLoverReq) ProtoMessage()    {}
func (*UnBindLoverReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *UnBindLoverReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnBindLoverReq.Unmarshal(m, b)
}
func (m *UnBindLoverReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnBindLoverReq.Marshal(b, m, deterministic)
}
func (m *UnBindLoverReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnBindLoverReq.Merge(m, src)
}
func (m *UnBindLoverReq) XXX_Size() int {
	return xxx_messageInfo_UnBindLoverReq.Size(m)
}
func (m *UnBindLoverReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnBindLoverReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnBindLoverReq proto.InternalMessageInfo

func (m *UnBindLoverReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UnBindLoverReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UnBindLoverReq) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *UnBindLoverReq) GetUnBindLoverInfo() *LoverInfo {
	if m != nil {
		return m.UnBindLoverInfo
	}
	return nil
}

type UnBindLoverResp struct {
	UnBindTime           string   `protobuf:"bytes,1,opt,name=UnBindTime,proto3" json:"UnBindTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnBindLoverResp) Reset()         { *m = UnBindLoverResp{} }
func (m *UnBindLoverResp) String() string { return proto.CompactTextString(m) }
func (*UnBindLoverResp) ProtoMessage()    {}
func (*UnBindLoverResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *UnBindLoverResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnBindLoverResp.Unmarshal(m, b)
}
func (m *UnBindLoverResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnBindLoverResp.Marshal(b, m, deterministic)
}
func (m *UnBindLoverResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnBindLoverResp.Merge(m, src)
}
func (m *UnBindLoverResp) XXX_Size() int {
	return xxx_messageInfo_UnBindLoverResp.Size(m)
}
func (m *UnBindLoverResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UnBindLoverResp.DiscardUnknown(m)
}

var xxx_messageInfo_UnBindLoverResp proto.InternalMessageInfo

func (m *UnBindLoverResp) GetUnBindTime() string {
	if m != nil {
		return m.UnBindTime
	}
	return ""
}

type GetLoverInfoReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLoverInfoReq) Reset()         { *m = GetLoverInfoReq{} }
func (m *GetLoverInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetLoverInfoReq) ProtoMessage()    {}
func (*GetLoverInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{13}
}

func (m *GetLoverInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLoverInfoReq.Unmarshal(m, b)
}
func (m *GetLoverInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLoverInfoReq.Marshal(b, m, deterministic)
}
func (m *GetLoverInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLoverInfoReq.Merge(m, src)
}
func (m *GetLoverInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetLoverInfoReq.Size(m)
}
func (m *GetLoverInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLoverInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetLoverInfoReq proto.InternalMessageInfo

func (m *GetLoverInfoReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetLoverInfoReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type GetLoverInfoResp struct {
	GotLoverInfo         *LoverInfo `protobuf:"bytes,1,opt,name=GotLoverInfo,proto3" json:"GotLoverInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetLoverInfoResp) Reset()         { *m = GetLoverInfoResp{} }
func (m *GetLoverInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetLoverInfoResp) ProtoMessage()    {}
func (*GetLoverInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{14}
}

func (m *GetLoverInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLoverInfoResp.Unmarshal(m, b)
}
func (m *GetLoverInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLoverInfoResp.Marshal(b, m, deterministic)
}
func (m *GetLoverInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLoverInfoResp.Merge(m, src)
}
func (m *GetLoverInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetLoverInfoResp.Size(m)
}
func (m *GetLoverInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLoverInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetLoverInfoResp proto.InternalMessageInfo

func (m *GetLoverInfoResp) GetGotLoverInfo() *LoverInfo {
	if m != nil {
		return m.GotLoverInfo
	}
	return nil
}

//用户账户相关操作
type QueryUserIsExistByIdReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserIsExistByIdReq) Reset()         { *m = QueryUserIsExistByIdReq{} }
func (m *QueryUserIsExistByIdReq) String() string { return proto.CompactTextString(m) }
func (*QueryUserIsExistByIdReq) ProtoMessage()    {}
func (*QueryUserIsExistByIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{15}
}

func (m *QueryUserIsExistByIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserIsExistByIdReq.Unmarshal(m, b)
}
func (m *QueryUserIsExistByIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserIsExistByIdReq.Marshal(b, m, deterministic)
}
func (m *QueryUserIsExistByIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserIsExistByIdReq.Merge(m, src)
}
func (m *QueryUserIsExistByIdReq) XXX_Size() int {
	return xxx_messageInfo_QueryUserIsExistByIdReq.Size(m)
}
func (m *QueryUserIsExistByIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserIsExistByIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserIsExistByIdReq proto.InternalMessageInfo

func (m *QueryUserIsExistByIdReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type QueryUserIsExistByIdResp struct {
	IsExist              bool     `protobuf:"varint,1,opt,name=IsExist,proto3" json:"IsExist,omitempty"`
	QueryCode            int32    `protobuf:"varint,2,opt,name=QueryCode,proto3" json:"QueryCode,omitempty"`
	QueryRes             string   `protobuf:"bytes,3,opt,name=QueryRes,proto3" json:"QueryRes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserIsExistByIdResp) Reset()         { *m = QueryUserIsExistByIdResp{} }
func (m *QueryUserIsExistByIdResp) String() string { return proto.CompactTextString(m) }
func (*QueryUserIsExistByIdResp) ProtoMessage()    {}
func (*QueryUserIsExistByIdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{16}
}

func (m *QueryUserIsExistByIdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserIsExistByIdResp.Unmarshal(m, b)
}
func (m *QueryUserIsExistByIdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserIsExistByIdResp.Marshal(b, m, deterministic)
}
func (m *QueryUserIsExistByIdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserIsExistByIdResp.Merge(m, src)
}
func (m *QueryUserIsExistByIdResp) XXX_Size() int {
	return xxx_messageInfo_QueryUserIsExistByIdResp.Size(m)
}
func (m *QueryUserIsExistByIdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserIsExistByIdResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserIsExistByIdResp proto.InternalMessageInfo

func (m *QueryUserIsExistByIdResp) GetIsExist() bool {
	if m != nil {
		return m.IsExist
	}
	return false
}

func (m *QueryUserIsExistByIdResp) GetQueryCode() int32 {
	if m != nil {
		return m.QueryCode
	}
	return 0
}

func (m *QueryUserIsExistByIdResp) GetQueryRes() string {
	if m != nil {
		return m.QueryRes
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginInfo)(nil), "lovers.srv.user.LoginInfo")
	proto.RegisterType((*BaseInfo)(nil), "lovers.srv.user.BaseInfo")
	proto.RegisterType((*LoverInfo)(nil), "lovers.srv.user.LoverInfo")
	proto.RegisterType((*LoginReq)(nil), "lovers.srv.user.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "lovers.srv.user.LoginResp")
	proto.RegisterType((*LogoutReq)(nil), "lovers.srv.user.LogoutReq")
	proto.RegisterType((*LogoutResp)(nil), "lovers.srv.user.LogoutResp")
	proto.RegisterType((*RegisterReq)(nil), "lovers.srv.user.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "lovers.srv.user.RegisterResp")
	proto.RegisterType((*BindLoverReq)(nil), "lovers.srv.user.BindLoverReq")
	proto.RegisterType((*BindLoverResp)(nil), "lovers.srv.user.BindLoverResp")
	proto.RegisterType((*UnBindLoverReq)(nil), "lovers.srv.user.UnBindLoverReq")
	proto.RegisterType((*UnBindLoverResp)(nil), "lovers.srv.user.UnBindLoverResp")
	proto.RegisterType((*GetLoverInfoReq)(nil), "lovers.srv.user.GetLoverInfoReq")
	proto.RegisterType((*GetLoverInfoResp)(nil), "lovers.srv.user.GetLoverInfoResp")
	proto.RegisterType((*QueryUserIsExistByIdReq)(nil), "lovers.srv.user.QueryUserIsExistByIdReq")
	proto.RegisterType((*QueryUserIsExistByIdResp)(nil), "lovers.srv.user.QueryUserIsExistByIdResp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 823 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x4e, 0xdb, 0x48,
	0x14, 0x5e, 0xe7, 0x8f, 0xe4, 0x24, 0xfc, 0x68, 0x84, 0x58, 0xe3, 0x65, 0xb3, 0xd9, 0xd1, 0x5e,
	0xb0, 0x37, 0x91, 0x60, 0xb5, 0x17, 0x2b, 0xad, 0x76, 0x69, 0xa0, 0xa2, 0x91, 0x28, 0xa2, 0x26,
	0xb4, 0x77, 0x95, 0x52, 0x3c, 0x80, 0x05, 0xf1, 0x18, 0x8f, 0x43, 0xc9, 0x03, 0xf4, 0xb6, 0x7d,
	0x85, 0x3e, 0x42, 0x1f, 0xa2, 0x0f, 0xd1, 0x07, 0xe9, 0x03, 0x54, 0x73, 0xc6, 0x63, 0x8f, 0xf3,
	0x0b, 0xe2, 0xce, 0xe7, 0x3b, 0xff, 0xe7, 0x3b, 0x73, 0x64, 0x80, 0xa1, 0x60, 0x51, 0x3b, 0x8c,
	0x78, 0xcc, 0xc9, 0xea, 0x0d, 0xbf, 0x63, 0x91, 0x68, 0x8b, 0xe8, 0xae, 0x2d, 0x61, 0xfa, 0xc1,
	0x82, 0xda, 0x11, 0xbf, 0xf4, 0x83, 0x6e, 0x70, 0xc1, 0xc9, 0x06, 0x54, 0xce, 0x04, 0x8b, 0xba,
	0x9e, 0x6d, 0xb5, 0xac, 0xed, 0x9a, 0x9b, 0x48, 0xc4, 0x81, 0xaa, 0xfc, 0x3a, 0xee, 0x0f, 0x98,
	0x5d, 0x40, 0x4d, 0x2a, 0x4b, 0xdd, 0x49, 0x5f, 0x88, 0x37, 0x3c, 0xf2, 0xec, 0xa2, 0xd2, 0x69,
	0x99, 0xac, 0x43, 0xf9, 0xe4, 0x8a, 0x07, 0xcc, 0x2e, 0xa1, 0x42, 0x09, 0x84, 0x40, 0xa9, 0x37,
	0x0a, 0x99, 0x5d, 0x46, 0x10, 0xbf, 0xe9, 0x77, 0x0b, 0xaa, 0x9d, 0xbe, 0x60, 0x8b, 0xca, 0x70,
	0x59, 0xff, 0xc6, 0x2c, 0x43, 0xcb, 0x59, 0xaa, 0xa2, 0x99, 0x6a, 0x0d, 0x8a, 0xa7, 0xec, 0x3e,
	0x49, 0x2f, 0x3f, 0xa5, 0x5d, 0xc7, 0x8f, 0xe2, 0xab, 0x24, 0xbb, 0x12, 0xc8, 0x16, 0xd4, 0x4e,
	0xcf, 0x87, 0x37, 0x61, 0x3c, 0x8c, 0x98, 0x5d, 0x41, 0x4d, 0x06, 0xc8, 0xbc, 0x2f, 0xf8, 0x80,
	0xf5, 0xf8, 0xfb, 0xc0, 0x5e, 0x52, 0x79, 0xb5, 0x4c, 0xfe, 0x85, 0xfa, 0xb3, 0x80, 0xc7, 0x57,
	0x2c, 0x92, 0xa5, 0xdb, 0xd5, 0x96, 0xb5, 0x5d, 0xdf, 0x75, 0xda, 0x63, 0x73, 0x6e, 0x1f, 0x49,
	0x59, 0x5a, 0xb8, 0xa6, 0x39, 0xfd, 0x84, 0xe3, 0x4f, 0x54, 0xc4, 0x86, 0x25, 0x25, 0xe8, 0xc6,
	0xb5, 0x48, 0x9a, 0x00, 0xf8, 0xa9, 0x5a, 0x54, 0xbd, 0x1b, 0x08, 0xf9, 0x03, 0x96, 0x51, 0x3a,
	0xf6, 0xcf, 0xaf, 0x71, 0x3c, 0x6a, 0x0a, 0x79, 0x90, 0x50, 0x68, 0x48, 0xe0, 0x60, 0x18, 0xf5,
	0x63, 0x9f, 0x07, 0xc9, 0x58, 0x72, 0x18, 0xfd, 0x68, 0x41, 0x15, 0x17, 0xc2, 0x65, 0xb7, 0x39,
	0xde, 0xad, 0x39, 0xbc, 0x17, 0xc6, 0x78, 0xd7, 0x0c, 0x17, 0x33, 0x86, 0x67, 0xec, 0x42, 0x0b,
	0xea, 0xaf, 0x59, 0x14, 0xfb, 0x17, 0xa3, 0x7d, 0xee, 0xe9, 0x95, 0x30, 0x21, 0xfa, 0x45, 0x6f,
	0xa8, 0xcb, 0x44, 0x28, 0xa3, 0xf4, 0xf8, 0x35, 0x0b, 0x92, 0x72, 0x94, 0x40, 0xfe, 0x56, 0x75,
	0x22, 0x03, 0x05, 0x64, 0x60, 0x73, 0x82, 0x01, 0xbd, 0x5d, 0x6e, 0x6a, 0x2a, 0x59, 0xc7, 0xc8,
	0x3d, 0x3f, 0x9d, 0x58, 0x06, 0xc8, 0x06, 0x75, 0xde, 0xa4, 0xe6, 0x54, 0x4e, 0x3d, 0x8d, 0xa2,
	0x33, 0x80, 0xfe, 0x83, 0x5a, 0x3e, 0x8c, 0xe5, 0x0c, 0xd3, 0xbe, 0x2d, 0xb3, 0xef, 0x6c, 0xc5,
	0x0b, 0xe6, 0x8a, 0xd3, 0x8e, 0x24, 0x5a, 0xb9, 0xaa, 0x6e, 0xa7, 0xf8, 0x36, 0xb5, 0x0d, 0xd6,
	0x9d, 0x2e, 0x83, 0x46, 0xe8, 0x37, 0x0b, 0xea, 0x2e, 0xbb, 0xf4, 0x45, 0xcc, 0xa2, 0xa7, 0xb0,
	0x68, 0x4e, 0xb5, 0xf8, 0xf0, 0xa9, 0x6e, 0x40, 0xa5, 0xe3, 0x07, 0x5e, 0xd7, 0x4b, 0xa6, 0x96,
	0x48, 0x92, 0x6a, 0x97, 0x9d, 0xf3, 0xc1, 0x80, 0x05, 0x5e, 0xf7, 0x40, 0x53, 0x6d, 0x40, 0xe3,
	0xcb, 0x50, 0x99, 0x5c, 0x06, 0x17, 0x1a, 0x59, 0x67, 0x22, 0x24, 0x1d, 0x58, 0xd1, 0x32, 0xf3,
	0xb0, 0x50, 0x6b, 0xe6, 0x03, 0x4c, 0x56, 0xc8, 0x1d, 0xf3, 0xa0, 0x6f, 0xa1, 0x21, 0x2b, 0xc4,
	0xa7, 0x22, 0xc7, 0x35, 0xeb, 0xfa, 0xa4, 0x64, 0x14, 0xc6, 0x16, 0x38, 0xf5, 0xee, 0xea, 0x0b,
	0x68, 0x42, 0x74, 0x00, 0xcb, 0x46, 0x7c, 0x11, 0x92, 0x3d, 0x03, 0x58, 0x50, 0xb3, 0x3e, 0x1a,
	0x79, 0x07, 0xc9, 0x9a, 0x04, 0x0c, 0xfe, 0x53, 0x99, 0x7e, 0xb6, 0x60, 0xe5, 0x2c, 0x78, 0x42,
	0x47, 0xf3, 0x0e, 0xfa, 0x01, 0xac, 0x1a, 0xb1, 0xb1, 0xf8, 0xd2, 0xc2, 0xe2, 0xc7, 0x5d, 0xe8,
	0x4e, 0x2e, 0x0a, 0xce, 0xa4, 0x09, 0xa0, 0x20, 0xec, 0x49, 0x95, 0x69, 0x20, 0xf4, 0x7f, 0x58,
	0x3d, 0x64, 0x71, 0x16, 0xf3, 0xb1, 0x5d, 0x51, 0x17, 0xd6, 0xf2, 0x01, 0x44, 0x48, 0xfe, 0x83,
	0xc6, 0x21, 0x8f, 0x1f, 0xc3, 0x43, 0xce, 0x9e, 0xee, 0xc0, 0xcf, 0xaf, 0x86, 0x2c, 0x1a, 0x61,
	0x62, 0xf1, 0xfc, 0xde, 0x17, 0x71, 0x67, 0xd4, 0xf5, 0xe6, 0x14, 0x47, 0x03, 0xb0, 0xa7, 0xbb,
	0x88, 0x50, 0x9e, 0xff, 0x04, 0x42, 0xa7, 0xaa, 0xab, 0x45, 0x79, 0x6e, 0xd0, 0x0b, 0x9f, 0x85,
	0x6c, 0xab, 0xec, 0x66, 0x80, 0x24, 0x0c, 0x05, 0x79, 0xa8, 0x12, 0xc2, 0xb4, 0xbc, 0xfb, 0xb5,
	0x04, 0x25, 0x99, 0x8b, 0xec, 0x41, 0x19, 0x9f, 0x00, 0xd9, 0x9c, 0xf5, 0x34, 0x6e, 0x9d, 0x39,
	0xaf, 0x86, 0xfe, 0x44, 0xf6, 0xa1, 0xa2, 0x8e, 0x0c, 0x99, 0x6a, 0xa7, 0xce, 0x9d, 0xf3, 0xcb,
	0x4c, 0x1d, 0x06, 0x79, 0x99, 0x3d, 0x60, 0x2c, 0x6b, 0x6b, 0xc2, 0xdc, 0xb8, 0x5c, 0xce, 0xaf,
	0x73, 0xb4, 0x18, 0xee, 0x08, 0x6a, 0xe9, 0x1e, 0x91, 0x49, 0x6b, 0xf3, 0x15, 0x38, 0xcd, 0x79,
	0x6a, 0x8c, 0xe6, 0x42, 0xdd, 0xd8, 0x4b, 0xf2, 0xdb, 0x84, 0x43, 0xfe, 0x5d, 0x39, 0xad, 0xf9,
	0x06, 0x18, 0xf3, 0x0c, 0x1a, 0xe6, 0xde, 0x91, 0x49, 0x9f, 0xb1, 0xbd, 0x76, 0x7e, 0x5f, 0x60,
	0x81, 0x61, 0x07, 0xb0, 0x3e, 0x6d, 0x8f, 0xc8, 0xf6, 0x84, 0xf3, 0x8c, 0x0d, 0x75, 0xfe, 0x7c,
	0xa0, 0xa5, 0x4c, 0xf7, 0xae, 0x82, 0xbf, 0x8f, 0x7f, 0xfd, 0x08, 0x00, 0x00, 0xff, 0xff, 0xab,
	0xe5, 0xdf, 0x19, 0x4c, 0x0a, 0x00, 0x00,
}
