// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: noteList.proto

package lovers_srv_noteList

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for NoteList service

type NoteListService interface {
	NoteListUp(ctx context.Context, in *NoteListUpReq, opts ...client.CallOption) (*NoteListUpResp, error)
	NoteListDown(ctx context.Context, in *NoteListDownReq, opts ...client.CallOption) (*NoteListDownResp, error)
	NoteListDel(ctx context.Context, in *NoteListDelReq, opts ...client.CallOption) (*NoteListDelResp, error)
}

type noteListService struct {
	c    client.Client
	name string
}

func NewNoteListService(name string, c client.Client) NoteListService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "lovers.srv.noteList"
	}
	return &noteListService{
		c:    c,
		name: name,
	}
}

func (c *noteListService) NoteListUp(ctx context.Context, in *NoteListUpReq, opts ...client.CallOption) (*NoteListUpResp, error) {
	req := c.c.NewRequest(c.name, "NoteList.NoteListUp", in)
	out := new(NoteListUpResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteListService) NoteListDown(ctx context.Context, in *NoteListDownReq, opts ...client.CallOption) (*NoteListDownResp, error) {
	req := c.c.NewRequest(c.name, "NoteList.NoteListDown", in)
	out := new(NoteListDownResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteListService) NoteListDel(ctx context.Context, in *NoteListDelReq, opts ...client.CallOption) (*NoteListDelResp, error) {
	req := c.c.NewRequest(c.name, "NoteList.NoteListDel", in)
	out := new(NoteListDelResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NoteList service

type NoteListHandler interface {
	NoteListUp(context.Context, *NoteListUpReq, *NoteListUpResp) error
	NoteListDown(context.Context, *NoteListDownReq, *NoteListDownResp) error
	NoteListDel(context.Context, *NoteListDelReq, *NoteListDelResp) error
}

func RegisterNoteListHandler(s server.Server, hdlr NoteListHandler, opts ...server.HandlerOption) error {
	type noteList interface {
		NoteListUp(ctx context.Context, in *NoteListUpReq, out *NoteListUpResp) error
		NoteListDown(ctx context.Context, in *NoteListDownReq, out *NoteListDownResp) error
		NoteListDel(ctx context.Context, in *NoteListDelReq, out *NoteListDelResp) error
	}
	type NoteList struct {
		noteList
	}
	h := &noteListHandler{hdlr}
	return s.Handle(s.NewHandler(&NoteList{h}, opts...))
}

type noteListHandler struct {
	NoteListHandler
}

func (h *noteListHandler) NoteListUp(ctx context.Context, in *NoteListUpReq, out *NoteListUpResp) error {
	return h.NoteListHandler.NoteListUp(ctx, in, out)
}

func (h *noteListHandler) NoteListDown(ctx context.Context, in *NoteListDownReq, out *NoteListDownResp) error {
	return h.NoteListHandler.NoteListDown(ctx, in, out)
}

func (h *noteListHandler) NoteListDel(ctx context.Context, in *NoteListDelReq, out *NoteListDelResp) error {
	return h.NoteListHandler.NoteListDel(ctx, in, out)
}
