// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: notelist.proto

package lovers_srv_noteList

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NoteListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoteListReq) Reset() {
	*x = NoteListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notelist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoteListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteListReq) ProtoMessage() {}

func (x *NoteListReq) ProtoReflect() protoreflect.Message {
	mi := &file_notelist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteListReq.ProtoReflect.Descriptor instead.
func (*NoteListReq) Descriptor() ([]byte, []int) {
	return file_notelist_proto_rawDescGZIP(), []int{0}
}

type NoteListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoteListResp) Reset() {
	*x = NoteListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notelist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoteListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteListResp) ProtoMessage() {}

func (x *NoteListResp) ProtoReflect() protoreflect.Message {
	mi := &file_notelist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteListResp.ProtoReflect.Descriptor instead.
func (*NoteListResp) Descriptor() ([]byte, []int) {
	return file_notelist_proto_rawDescGZIP(), []int{1}
}

type BaseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string     `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	NoteListOpt string     `protobuf:"bytes,2,opt,name=NoteListOpt,proto3" json:"NoteListOpt,omitempty"` //获取还是上传事件清单
	AnotherInfo *LoverInfo `protobuf:"bytes,8,opt,name=AnotherInfo,proto3" json:"AnotherInfo,omitempty"`
}

func (x *BaseInfo) Reset() {
	*x = BaseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notelist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfo) ProtoMessage() {}

func (x *BaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notelist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfo.ProtoReflect.Descriptor instead.
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return file_notelist_proto_rawDescGZIP(), []int{2}
}

func (x *BaseInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BaseInfo) GetNoteListOpt() string {
	if x != nil {
		return x.NoteListOpt
	}
	return ""
}

func (x *BaseInfo) GetAnotherInfo() *LoverInfo {
	if x != nil {
		return x.AnotherInfo
	}
	return nil
}

type LoverInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoverId       string `protobuf:"bytes,1,opt,name=LoverId,proto3" json:"LoverId,omitempty"`
	LoverPhone    string `protobuf:"bytes,2,opt,name=LoverPhone,proto3" json:"LoverPhone,omitempty"`
	LoverNickName string `protobuf:"bytes,3,opt,name=LoverNickName,proto3" json:"LoverNickName,omitempty"`
	LoverDuration string `protobuf:"bytes,4,opt,name=LoverDuration,proto3" json:"LoverDuration,omitempty"`
}

func (x *LoverInfo) Reset() {
	*x = LoverInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notelist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoverInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoverInfo) ProtoMessage() {}

func (x *LoverInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notelist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoverInfo.ProtoReflect.Descriptor instead.
func (*LoverInfo) Descriptor() ([]byte, []int) {
	return file_notelist_proto_rawDescGZIP(), []int{3}
}

func (x *LoverInfo) GetLoverId() string {
	if x != nil {
		return x.LoverId
	}
	return ""
}

func (x *LoverInfo) GetLoverPhone() string {
	if x != nil {
		return x.LoverPhone
	}
	return ""
}

func (x *LoverInfo) GetLoverNickName() string {
	if x != nil {
		return x.LoverNickName
	}
	return ""
}

func (x *LoverInfo) GetLoverDuration() string {
	if x != nil {
		return x.LoverDuration
	}
	return ""
}

var File_notelist_proto protoreflect.FileDescriptor

var file_notelist_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6e, 0x6f, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x13, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x6e, 0x6f, 0x74,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x4e, 0x6f, 0x74, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x22, 0x0e, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x86, 0x01, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x6f, 0x74,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x4e, 0x6f, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x12, 0x40, 0x0a, 0x0b, 0x41,
	0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x6e, 0x6f,
	0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x4c, 0x6f, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0b, 0x41, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x91, 0x01,
	0x0a, 0x09, 0x4c, 0x6f, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x4c,
	0x6f, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x6f,
	0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x6f, 0x76, 0x65, 0x72, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4c, 0x6f, 0x76, 0x65, 0x72,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x4c, 0x6f, 0x76, 0x65, 0x72, 0x4e, 0x69,
	0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x4c, 0x6f,
	0x76, 0x65, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x4c,
	0x6f, 0x76, 0x65, 0x72, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x4c, 0x6f, 0x76, 0x65, 0x72, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x32, 0xbf, 0x01, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x57,
	0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x20, 0x2e, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x6e,
	0x6f, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x72, 0x76,
	0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x2e, 0x6c, 0x6f,
	0x76, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x1a, 0x21,
	0x2e, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x6e, 0x6f, 0x74, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notelist_proto_rawDescOnce sync.Once
	file_notelist_proto_rawDescData = file_notelist_proto_rawDesc
)

func file_notelist_proto_rawDescGZIP() []byte {
	file_notelist_proto_rawDescOnce.Do(func() {
		file_notelist_proto_rawDescData = protoimpl.X.CompressGZIP(file_notelist_proto_rawDescData)
	})
	return file_notelist_proto_rawDescData
}

var file_notelist_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_notelist_proto_goTypes = []interface{}{
	(*NoteListReq)(nil),  // 0: lovers.srv.noteList.NoteListReq
	(*NoteListResp)(nil), // 1: lovers.srv.noteList.NoteListResp
	(*BaseInfo)(nil),     // 2: lovers.srv.noteList.BaseInfo
	(*LoverInfo)(nil),    // 3: lovers.srv.noteList.LoverInfo
}
var file_notelist_proto_depIdxs = []int32{
	3, // 0: lovers.srv.noteList.BaseInfo.AnotherInfo:type_name -> lovers.srv.noteList.LoverInfo
	0, // 1: lovers.srv.noteList.NoteList.RequestNoteList:input_type -> lovers.srv.noteList.NoteListReq
	1, // 2: lovers.srv.noteList.NoteList.ResponseNoteList:input_type -> lovers.srv.noteList.NoteListResp
	0, // 3: lovers.srv.noteList.NoteList.RequestNoteList:output_type -> lovers.srv.noteList.NoteListReq
	1, // 4: lovers.srv.noteList.NoteList.ResponseNoteList:output_type -> lovers.srv.noteList.NoteListResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_notelist_proto_init() }
func file_notelist_proto_init() {
	if File_notelist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notelist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoteListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notelist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoteListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notelist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notelist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoverInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notelist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notelist_proto_goTypes,
		DependencyIndexes: file_notelist_proto_depIdxs,
		MessageInfos:      file_notelist_proto_msgTypes,
	}.Build()
	File_notelist_proto = out.File
	file_notelist_proto_rawDesc = nil
	file_notelist_proto_goTypes = nil
	file_notelist_proto_depIdxs = nil
}
